package Kiran.java.demo_usermanagement.entity;

import jakarta.persistence.*;


@Entity
// @Entity Marks this class as a JPA entity
//Tells Hibernate to map it to a database table
@Table(name="users")

//Specifies the table name
//Without this, table name defaults to class name (User)

public class User {
   @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)

   //@Id → Marks primary key
   //@GeneratedValue → ID is auto-generated by the database
    private Long id;
    private String firstName;
    private String lastName;

    @Column(unique = true)
    private String email;

    public User() {

    }

    public User(Long id, String firstName, String lastName, String email) {
        this.id = id;
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }
}


//This User class is a JPA entity that maps to the users table in the database. The @Entity and @Table annotations define the mapping, while fields represent columns.
// The id is the primary key with auto-generation, and the email field is enforced as unique. Hibernate manages this entity and automatically converts it into SQL operations.


//JPA needs a default constructor
//Follows POJO + ORM concept
//Hibernate handles mapping automatically
//Field names can be customized using @Column